// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./providers"; // <-- import our client wrapper
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import DndProviderWrapper from "./components/DndProviderWrapper";
import { Toaster } from 'react-hot-toast';
import { EnrollmentCheckProvider } from './contexts/EnrollmentCheckContext';

// These font imports are still valid in a server component
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <EnrollmentCheckProvider>
            <Providers>
              <DndProviderWrapper>{children}</DndProviderWrapper>
            </Providers>
            <Toaster />
          </EnrollmentCheckProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
